server:
  port: 8081
  
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/billDB
    password: 16305170.mmk
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect 
    
  application:
    name: BILL-SERVICE